# Generated by Django 5.1.6 on 2025-10-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_suhu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturereading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
